module.exports = {
    columnCount: true,
    columns: true,
    fontWeight: true,
    lineHeight: true,
    opacity: true,
    zIndex: true,
    zoom: true,
    animationIterationCount: true,
    boxFlex: true,
    boxFlexGroup: true,
    boxOrdinalGroup: true,
    flex: true,
    flexGrow: true,
    flexPositive: true,
    flexShrink: true,
    flexNegative: true,
    flexOrder: true,
    lineClamp: true,
    order: true,
    orphans: true,
    tabSize: true,
    widows: true,
    // SVG-related properties
    fillOpacity: true,
    stopOpacity: true,
    strokeDashoffset: true,
    strokeOpacity: true,
    strokeWidth: true
};